Fallback to regular python when python_d is not found for windows debug build
ros2/python_cmake_module pull request #15
Opened 2024-06-19 06:49 UTC by felixf4xu

Hi,

I had a cmake error when using `python_cmake_module` when I build a Windows dubug version of ros2, and I don't have `python_d.exe`.

This PR fix this error, by use the fallback value of `${PYTHON_EXECUTABLE}` for cmake variable of `PYTHON_EXECUTABLE_DEBUG`, then later usage of `PYTHON_EXECUTABLE_DEBUG` 
```
set(Python3_EXECUTABLE "${PYTHON_EXECUTABLE_DEBUG}")
set_property(TARGET Python3::Interpreter PROPERTY IMPORTED_LOCATION "${PYTHON_EXECUTABLE_DEBUG}")
```
will not have an error.

2024-06-20 16:52 UTC, clalancette requested changes
I'm not totally convinced we want to do this.

However, whether I agree or not is a bit moot.  I'm actively trying to deprecate and remove this entire package (see https://github.com/ros2/ros2/pull/1524), so I don't think we should make a change like this at this time in `rolling`.  I'm going to leave this as "Request changes" for now, and will probably close it out once we actually get the above landed.

2024-06-21 00:42 UTC, felixf4xu commented
I'm fine if this package is removed.

Some more notes about the situation: Building ROS2 on Windows for Debug build. 

Current implementation requires a debug version of python, (like python_d.exe), which in my opinion, is not a necessary. It should be possible to install python (not debug) and then compile ROS2 on windows for debug build, or in other words, Release version of python can also be used to build a debug version of ROS2.

2024-06-21 14:57 UTC, clalancette commented
> Current implementation requires a debug version of python, (like python_d.exe), which in my opinion, is not a necessary. It should be possible to install python (not debug) and then compile ROS2 on windows for debug build, or in other words, Release version of python can also be used to build a debug version of ROS2.

Yes and no.  You are correct that you can build the C++ stuff in Debug mode while still using the Python release stuff, and things will generally work.  But you won't get the extra debugging information when you are debugging Python things.

Regardless, that will become moot once we remove this package.  In that case, if you want to use an alternate interpreter than what the system default is, you'll have to explicitly pass a `Python3_EXECUTABLE` parameter to `colcon`.  On the buildfarm we'll continue to point that to a debug Python interpreter, but if you don't want to, you don't have to.

2024-06-22 09:20 UTC, felixf4xu commented
> you won't get the extra debugging information when you are debugging Python things

Thanks for mentioning the debugging information, in that case, I still think it should not be a cmake error, a cmake warning (there already is a warning) should be good enough.

> if you want to use an alternate interpreter than what the system default is

That's exactly what the PR is doing, fallback to system default: If you have python_d in the building system, use it and generate debug information for debugging Python things; if not, give a warning, and then continue to build.

2024-10-03 18:25 UTC, clalancette commented
Given that I just merged in https://github.com/ros2/ros2/pull/1524 , this repository is now obsolete.  It will obviously still be kept around for the released distributions (Jazzy, Humble, and Iron), but we shouldn't need any changes going forward with Rolling or Kilted.

Because of that, I'm going to close this out.  If you want to have this functionality on older distributions, please feel free to reopen, targeting the branch that you are interested in.  Thanks for the contribution!

2024-10-03 18:25 UTC, closed without merging